/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface HealthChainCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_DID_LENGTH"
      | "SCHEMA_VERSION"
      | "VERSION"
      | "acceptOwnership"
      | "anchorCount"
      | "anchorRoot"
      | "authorizeIssuer"
      | "authorizedIssuers"
      | "deauthorizeIssuer"
      | "getAnchorAt"
      | "getLatestRoot"
      | "getRootAtTime"
      | "hasAnchors"
      | "issuerDids"
      | "issuerNames"
      | "owner"
      | "pendingOwner"
      | "revokeAnchor"
      | "transferOwnership"
      | "verifyCredential"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AnchorRevoked"
      | "IssuerAuthorized"
      | "IssuerDeauthorized"
      | "OwnershipTransferInitiated"
      | "OwnershipTransferred"
      | "RootAnchored"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_DID_LENGTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SCHEMA_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "VERSION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "anchorCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "anchorRoot",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeIssuer",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedIssuers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deauthorizeIssuer",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAnchorAt",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestRoot",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRootAtTime",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "hasAnchors", values: [string]): string;
  encodeFunctionData(
    functionFragment: "issuerDids",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issuerNames",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAnchor",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCredential",
    values: [string, BytesLike, BytesLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_DID_LENGTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SCHEMA_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "VERSION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "anchorCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "anchorRoot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizeIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedIssuers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deauthorizeIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAnchorAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRootAtTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasAnchors", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "issuerDids", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "issuerNames",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAnchor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyCredential",
    data: BytesLike
  ): Result;
}

export namespace AnchorRevokedEvent {
  export type InputTuple = [
    patientDidHash: BytesLike,
    anchorIndex: BigNumberish,
    issuer: AddressLike,
    reason: string
  ];
  export type OutputTuple = [
    patientDidHash: string,
    anchorIndex: bigint,
    issuer: string,
    reason: string
  ];
  export interface OutputObject {
    patientDidHash: string;
    anchorIndex: bigint;
    issuer: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerAuthorizedEvent {
  export type InputTuple = [
    issuer: AddressLike,
    issuerDid: string,
    name: string
  ];
  export type OutputTuple = [issuer: string, issuerDid: string, name: string];
  export interface OutputObject {
    issuer: string;
    issuerDid: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerDeauthorizedEvent {
  export type InputTuple = [issuer: AddressLike, reason: string];
  export type OutputTuple = [issuer: string, reason: string];
  export interface OutputObject {
    issuer: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferInitiatedEvent {
  export type InputTuple = [
    currentOwner: AddressLike,
    pendingOwner: AddressLike
  ];
  export type OutputTuple = [currentOwner: string, pendingOwner: string];
  export interface OutputObject {
    currentOwner: string;
    pendingOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RootAnchoredEvent {
  export type InputTuple = [
    patientDidHash: BytesLike,
    merkleRoot: BytesLike,
    issuer: AddressLike,
    issuerDid: string,
    anchorIndex: BigNumberish,
    schemaVersion: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    patientDidHash: string,
    merkleRoot: string,
    issuer: string,
    issuerDid: string,
    anchorIndex: bigint,
    schemaVersion: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    patientDidHash: string;
    merkleRoot: string;
    issuer: string;
    issuerDid: string;
    anchorIndex: bigint;
    schemaVersion: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HealthChainCore extends BaseContract {
  connect(runner?: ContractRunner | null): HealthChainCore;
  waitForDeployment(): Promise<this>;

  interface: HealthChainCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_DID_LENGTH: TypedContractMethod<[], [bigint], "view">;

  SCHEMA_VERSION: TypedContractMethod<[], [bigint], "view">;

  VERSION: TypedContractMethod<[], [string], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  anchorCount: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  anchorRoot: TypedContractMethod<
    [patientDid: string, merkleRoot: BytesLike],
    [void],
    "nonpayable"
  >;

  authorizeIssuer: TypedContractMethod<
    [issuerAddress: AddressLike, issuerDid: string, name: string],
    [void],
    "nonpayable"
  >;

  authorizedIssuers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  deauthorizeIssuer: TypedContractMethod<
    [issuerAddress: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;

  getAnchorAt: TypedContractMethod<
    [patientDid: string, anchorIndex: BigNumberish],
    [
      [string, bigint, bigint, boolean, string] & {
        merkleRoot: string;
        timestamp: bigint;
        schemaVersion: bigint;
        revoked: boolean;
        issuerDid: string;
      }
    ],
    "view"
  >;

  getLatestRoot: TypedContractMethod<
    [patientDid: string],
    [
      [string, bigint, bigint, string, bigint] & {
        merkleRoot: string;
        timestamp: bigint;
        schemaVersion: bigint;
        issuerDid: string;
        anchorIndex: bigint;
      }
    ],
    "view"
  >;

  getRootAtTime: TypedContractMethod<
    [patientDid: string, targetTimestamp: BigNumberish],
    [
      [string, bigint, boolean] & {
        merkleRoot: string;
        timestamp: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;

  hasAnchors: TypedContractMethod<[patientDid: string], [boolean], "view">;

  issuerDids: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  issuerNames: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  revokeAnchor: TypedContractMethod<
    [patientDid: string, anchorIndex: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyCredential: TypedContractMethod<
    [patientDid: string, leaf: BytesLike, proof: BytesLike[]],
    [
      [boolean, bigint, boolean] & {
        valid: boolean;
        timestamp: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_DID_LENGTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SCHEMA_VERSION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "anchorCount"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "anchorRoot"
  ): TypedContractMethod<
    [patientDid: string, merkleRoot: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizeIssuer"
  ): TypedContractMethod<
    [issuerAddress: AddressLike, issuerDid: string, name: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizedIssuers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "deauthorizeIssuer"
  ): TypedContractMethod<
    [issuerAddress: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAnchorAt"
  ): TypedContractMethod<
    [patientDid: string, anchorIndex: BigNumberish],
    [
      [string, bigint, bigint, boolean, string] & {
        merkleRoot: string;
        timestamp: bigint;
        schemaVersion: bigint;
        revoked: boolean;
        issuerDid: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLatestRoot"
  ): TypedContractMethod<
    [patientDid: string],
    [
      [string, bigint, bigint, string, bigint] & {
        merkleRoot: string;
        timestamp: bigint;
        schemaVersion: bigint;
        issuerDid: string;
        anchorIndex: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRootAtTime"
  ): TypedContractMethod<
    [patientDid: string, targetTimestamp: BigNumberish],
    [
      [string, bigint, boolean] & {
        merkleRoot: string;
        timestamp: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasAnchors"
  ): TypedContractMethod<[patientDid: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "issuerDids"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "issuerNames"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "revokeAnchor"
  ): TypedContractMethod<
    [patientDid: string, anchorIndex: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyCredential"
  ): TypedContractMethod<
    [patientDid: string, leaf: BytesLike, proof: BytesLike[]],
    [
      [boolean, bigint, boolean] & {
        valid: boolean;
        timestamp: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "AnchorRevoked"
  ): TypedContractEvent<
    AnchorRevokedEvent.InputTuple,
    AnchorRevokedEvent.OutputTuple,
    AnchorRevokedEvent.OutputObject
  >;
  getEvent(
    key: "IssuerAuthorized"
  ): TypedContractEvent<
    IssuerAuthorizedEvent.InputTuple,
    IssuerAuthorizedEvent.OutputTuple,
    IssuerAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "IssuerDeauthorized"
  ): TypedContractEvent<
    IssuerDeauthorizedEvent.InputTuple,
    IssuerDeauthorizedEvent.OutputTuple,
    IssuerDeauthorizedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferInitiated"
  ): TypedContractEvent<
    OwnershipTransferInitiatedEvent.InputTuple,
    OwnershipTransferInitiatedEvent.OutputTuple,
    OwnershipTransferInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RootAnchored"
  ): TypedContractEvent<
    RootAnchoredEvent.InputTuple,
    RootAnchoredEvent.OutputTuple,
    RootAnchoredEvent.OutputObject
  >;

  filters: {
    "AnchorRevoked(bytes32,uint256,address,string)": TypedContractEvent<
      AnchorRevokedEvent.InputTuple,
      AnchorRevokedEvent.OutputTuple,
      AnchorRevokedEvent.OutputObject
    >;
    AnchorRevoked: TypedContractEvent<
      AnchorRevokedEvent.InputTuple,
      AnchorRevokedEvent.OutputTuple,
      AnchorRevokedEvent.OutputObject
    >;

    "IssuerAuthorized(address,string,string)": TypedContractEvent<
      IssuerAuthorizedEvent.InputTuple,
      IssuerAuthorizedEvent.OutputTuple,
      IssuerAuthorizedEvent.OutputObject
    >;
    IssuerAuthorized: TypedContractEvent<
      IssuerAuthorizedEvent.InputTuple,
      IssuerAuthorizedEvent.OutputTuple,
      IssuerAuthorizedEvent.OutputObject
    >;

    "IssuerDeauthorized(address,string)": TypedContractEvent<
      IssuerDeauthorizedEvent.InputTuple,
      IssuerDeauthorizedEvent.OutputTuple,
      IssuerDeauthorizedEvent.OutputObject
    >;
    IssuerDeauthorized: TypedContractEvent<
      IssuerDeauthorizedEvent.InputTuple,
      IssuerDeauthorizedEvent.OutputTuple,
      IssuerDeauthorizedEvent.OutputObject
    >;

    "OwnershipTransferInitiated(address,address)": TypedContractEvent<
      OwnershipTransferInitiatedEvent.InputTuple,
      OwnershipTransferInitiatedEvent.OutputTuple,
      OwnershipTransferInitiatedEvent.OutputObject
    >;
    OwnershipTransferInitiated: TypedContractEvent<
      OwnershipTransferInitiatedEvent.InputTuple,
      OwnershipTransferInitiatedEvent.OutputTuple,
      OwnershipTransferInitiatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RootAnchored(bytes32,bytes32,address,string,uint256,uint16,uint64)": TypedContractEvent<
      RootAnchoredEvent.InputTuple,
      RootAnchoredEvent.OutputTuple,
      RootAnchoredEvent.OutputObject
    >;
    RootAnchored: TypedContractEvent<
      RootAnchoredEvent.InputTuple,
      RootAnchoredEvent.OutputTuple,
      RootAnchoredEvent.OutputObject
    >;
  };
}
