/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HealthChainCore } from "./HealthChainCore";
export * as factories from "./factories";
export { HealthChainCore__factory } from "./factories/HealthChainCore__factory";
